name: Main workflow to build and test
on: [pull_request]
jobs:
  test:
    name: Test
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@nordlb-ui'
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/npm.lock') }}
      - name: Install packages
        run: npm install
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Serve Storybook and run tests
        run: npm run test-storybook:ci
